# Numpy implementation of one hidden layer

# Problem set
<pre>
ex	 inputs	  outputs

1	0	0	1	 0
2	1	1	1	 1
3	1	0	1	 1
4	0	1	1	 0


when 1st input is 0 the output is 0
when 1st input is 1 the output is 1
</pre>

# perceptron
<pre>
lets start with perceptron

Inputs--synapses--------neuron-------------------outputs
x1       w1

x2       w2       (neuron basical output 
                   is weighted sum of inputs,      Predicted output
                   weighted sum then goes to 
                   normalizing function(sigmoid 
                   function))
x3       w3
</pre>

In [ ]:
import numpy as np

In [32]:
#define sigmoid function
def sigmoid(x):
    return (1/(1+np.exp(-x)))

In [41]:
#define derivative
def derivatives_sigmoid(x):
    return x * (1 - x)

In [3]:
#training Input and output
training_inputs=np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
training_outputs=np.array([[0,1,1,0]]).T

In [34]:
#initializing weights
np.random.seed(1)
synaptic_weights =2* np.random.random((3,1))-1

In [38]:
#before training model
for iteration in range(1):
        input_layer=training_inputs
        outputs=sigmoid(np.dot(input_layer,synaptic_weights)) #weigthted sum passed to sigmoid function
print(outputs)

[[0.29929909]
 [0.44378327]
 [0.32511054]
 [0.41433436]]


In [39]:
for iteration in range(20000):
        input_layer=training_inputs
        outputs=sigmoid(np.dot(input_layer,synaptic_weights))
        error=training_outputs-outputs
        adjustments=error*sigmoid_derivative(outputs)
        synaptic_weights+=np.dot(input_layer.T,adjustments)

In [40]:
#we could see the accuracy has increased
outputs

array([[0.00679655],
       [0.99445597],
       [0.99548528],
       [0.005536  ]])

Numpy Implementation of one hidden layer

An MLP consists of multiple layers called Hidden Layers stacked in between the Input Layer and the Output Layer
we can see the above example with one hodden layer implementation

In [42]:
X=np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
y=np.array([[0,1,1,0]]).T

In [47]:
#Variable initialization
epoch=20000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer


In [48]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [49]:
for i in range(epoch):

#Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)
#Back Propogation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer *lr
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr


In [50]:
output

array([[0.05961063],
       [0.94830572],
       [0.95325865],
       [0.05504399]])